services:
  backend:
    build:
      context: ./django_proxy
    container_name: django_lm_backend
    env_file:
      - ./django_proxy/proxy_project/.env  # chargé au runtime, pas au build
    volumes:
      - ./django_proxy/data:/app/data
      - ./django_proxy:/app
      - /app/.venv
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - SKIP_CRAWL=true
    restart: always
  # --- FRONTEND CONTAINER ---
  frontend:
    build:
      context: ./website  # frontend folder path
    container_name: vite_lm_frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend
    restart: always
