services:
  # --- BACKEND CONTAINER ---
  backend:
    build:
      context: ./django_proxy  # backend folder path
    container_name: django_lm_backend
    volumes:
      - ./django_proxy/data:/app/data  # relative path for data
      - ./django_proxy:/app            #live-reload
      - /app/.venv
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - SKIP_CRAWL=false #Set this to true for fast restarting, it avoids to run the data crawling script
    restart: always
  # --- FRONTEND CONTAINER ---
  frontend:
    build:
      context: ./website  # frontend folder path
    container_name: vite_lm_frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend
    restart: always
